# Generated by Django 5.2.7 on 2025-11-10 13:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups_joined',
            field=models.ManyToManyField(blank=True, related_name='members_direct', through='users.GroupMembership', through_fields=('user', 'group'), to='users.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to=users.models.user_avatar_path),
        ),
    ]
