# Generated by Django 5.2.8 on 2025-12-12 17:17

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups_joined',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to=users.models.user_avatar_path),
        ),
    ]
