# Generated by Django 5.2.8 on 2026-02-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_groups_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
