# Generated by Django 5.2.7 on 2026-04-01 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardcollaborator',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='reminders.board'),
        ),
        migrations.AddField(
            model_name='boardcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reminders.board'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workgroup_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_data', to='reminders.boarditem'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reminders.workgroup'),
        ),
        migrations.AddField(
            model_name='board',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='reminders.workgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='boardcollaborator',
            unique_together={('board', 'user')},
        ),
        migrations.AddIndex(
            model_name='boarditem',
            index=models.Index(fields=['board'], name='reminders_b_board_i_617933_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdata',
            index=models.Index(fields=['assigned_to', 'is_completed'], name='reminders_t_assigne_7e42a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
