# Generated by Django 5.2.8 on 2025-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='state_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
