# Generated by Django 5.2.7 on 2026-05-08 19:55

import django.utils.timezone
from django.db import migrations, models


def ensure_boardcollaborator_table(apps, schema_editor):
    """Create table if 0001/0002 were applied before BoardCollaborator existed in 0001."""
    if 'reminders_boardcollaborator' in schema_editor.connection.introspection.table_names():
        return
    BoardCollaborator = apps.get_model('reminders', 'BoardCollaborator')
    schema_editor.create_model(BoardCollaborator)


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(ensure_boardcollaborator_table, migrations.RunPython.noop),
        migrations.AddField(
            model_name='boardcollaborator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardcollaborator',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято')], default='pending', max_length=20),
        ),
    ]
