# Generated by Django 5.2.7 on 2026-05-08 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcollaborator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardcollaborator',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято')], default='pending', max_length=20),
        ),
    ]
