# Generated by Django 5.2.8 on 2026-02-08 14:59

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_board_state_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('task', 'Напоминание/Задача'), ('sticker', 'Стикер/Заметка'), ('text', 'Текст'), ('arrow', 'Стрелка/Линия'), ('drawing', 'Рисунок (Paint)'), ('image', 'Картинка')], max_length=20)),
                ('geometry', models.JSONField(default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('content_payload', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='folder',
            name='board',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={},
        ),
        migrations.RemoveField(
            model_name='board',
            name='state_data',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='board',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='group',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='access_level',
            field=models.CharField(choices=[('read', 'Reading'), ('write', 'Editing'), ('admin', 'Admin')], default='read', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['group'], name='reminders_b_group_i_726648_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created_by'], name='reminders_b_created_386625_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='reminders_g_name_e80cae_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=django.contrib.postgres.indexes.GinIndex(fields=['settings'], name='group_settings_gin'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'group'], name='reminders_g_user_id_24e877_idx'),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reminders.board'),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_data', to='reminders.boarditem'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddIndex(
            model_name='boarditem',
            index=models.Index(fields=['board'], name='reminders_b_board_i_617933_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdata',
            index=models.Index(fields=['assigned_to', 'is_completed'], name='reminders_t_assigne_7e42a2_idx'),
        ),
    ]
