# ЗАМЕНИТЕ cloudreminders.nothingfull.space на свой домен во всех местах ниже.

# HTTP — отдаём ACME-проверку и редиректим всё остальное на HTTPS
server {
    listen 80;
    server_name cloudreminders.nothingfull.space;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name cloudreminders.nothingfull.space;
    client_max_body_size 10M;

    # Каталог live/ называется по ПЕРВОМУ домену из команды certbot
    ssl_certificate     /etc/letsencrypt/live/cloudreminders.nothingfull.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloudreminders.nothingfull.space/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    location /static/ {
        alias /static/;
        expires 30d;
        access_log off;
    }

    location /media/ {
        alias /media/;
        expires 30d;
        access_log off;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
